export const images=[
    {
      id:1,
      url:"https://images.pexels.com/photos/1054218/pexels-photo-1054218.jpeg?auto=compress&cs=tinysrgb"
    },
    {
      id:2,
      url:"https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb"
    },
    {
      id:3,
      url:"https://images.pexels.com/photos/983200/pexels-photo-983200.jpeg?auto=compress&cs=tinysrgb"
    },
    {
      id:4,
      url:"https://images.pexels.com/photos/772803/pexels-photo-772803.jpeg?auto=compress&cs=tinysrgb"
    },
    {
      id:5,
      url:"https://images.pexels.com/photos/35857/amazing-beautiful-breathtaking-clouds.jpg?auto=compress&cs=tinysrgb"
    },
    {
        id:6,
        url:"https://images.pexels.com/photos/1275415/pexels-photo-1275415.jpeg?auto=compress&cs=tinysrgb"
    }
  ]